name: assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-labels:
    name: Assign Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Add Labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          labels: |
            automated
            pull-request
