name: build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.21.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go Version
        run: go version
      - name: Install Dependencies
        run: go install
      - name: Run Tests
        run: go test
